"""Behavioral building blocks for ADC-based SerDes studies."""

from .adc import AdcQuantizationResult, EffectiveUniformAdc
from .adc_impairments import (
    SampledAdcImpairmentResult,
    apply_sampled_adc_impairments,
    synthesize_real_noise_from_one_sided_psd,
)
from .code_dfe import CodeDomainDfeResult, train_code_domain_dfe
from .code_ffe import CodeDomainFfeResult, train_code_domain_ffe

from .decision_point import (
    DecisionPointResult,
    evaluate_decision_point,
    gaussian_pam4_der,
    noise_autocorrelation_at_ui_lags,
    output_noise_psd_one_sided,
    pam4_unit_voltage_from_delivered_power,
    pam4_unit_voltage_from_outer_pp,
    required_pam4_dp_snr_db,
)
from .frequency_response import (
    FrequencyResponse,
    analytic_channel_response,
    analytic_high_loss_channel_response,
    cascade_responses,
    ctle_afe_response,
    frequency_to_impulse,
    load_touchstone_sdd21,
    rectangular_pulse_response,
    sample_cursor_taps,
    uniform_frequency_grid,
)
from .eye import (
    EyeDiagram,
    eye_diagram_from_symbol_pulse,
    main_cursor_index,
    pam4_symbol_sequence,
    synthesize_symbol_waveform,
)
from .fec import (
    RS_CORRECTABLE_SYMBOL_ERRORS,
    RS_FIRST_CONSECUTIVE_ROOT,
    RS_GENERATOR_COEFFICIENTS,
    RS_K_SYMBOLS,
    RS_N_SYMBOLS,
    RS_PARITY_SYMBOLS,
    RS_PRIMITIVE_POLYNOMIAL,
    RS_SYMBOL_BITS,
    Rs544CodewordResult,
    Rs544FecResult,
    Rs544Pam4Stream,
    evaluate_rs544_fec,
    generate_rs544_pam4_stream,
    gray_bits_to_pam4_symbols,
    pam4_symbols_to_gray_bits,
    required_pre_fec_ber_for_iid_post_ber,
)
from .signal_metrics import PaprResult, voltage_papr
from .transmitter import (
    apply_tx_pulse_shaping,
    apply_tx_pulse_shaping_to_channel,
    centered_symbol_pulse_response,
    tx_pulse_shaping_response,
    zoh_frequency_response,
)
from .vga import (
    flat_vga_response,
    peak_target_gain_db,
    worst_case_pam_waveform_peak_v,
)

__all__ = [
    "AdcQuantizationResult",
    "CodeDomainFfeResult",
    "CodeDomainDfeResult",
    "DecisionPointResult",
    "EyeDiagram",
    "EffectiveUniformAdc",
    "FrequencyResponse",
    "PaprResult",
    "RS_CORRECTABLE_SYMBOL_ERRORS",
    "RS_FIRST_CONSECUTIVE_ROOT",
    "RS_GENERATOR_COEFFICIENTS",
    "RS_K_SYMBOLS",
    "RS_N_SYMBOLS",
    "RS_PARITY_SYMBOLS",
    "RS_PRIMITIVE_POLYNOMIAL",
    "RS_SYMBOL_BITS",
    "Rs544CodewordResult",
    "Rs544FecResult",
    "Rs544Pam4Stream",
    "SampledAdcImpairmentResult",
    "analytic_channel_response",
    "analytic_high_loss_channel_response",
    "apply_tx_pulse_shaping",
    "apply_tx_pulse_shaping_to_channel",
    "apply_sampled_adc_impairments",
    "cascade_responses",
    "centered_symbol_pulse_response",
    "ctle_afe_response",
    "evaluate_decision_point",
    "evaluate_rs544_fec",
    "eye_diagram_from_symbol_pulse",
    "frequency_to_impulse",
    "flat_vga_response",
    "gaussian_pam4_der",
    "generate_rs544_pam4_stream",
    "gray_bits_to_pam4_symbols",
    "load_touchstone_sdd21",
    "main_cursor_index",
    "noise_autocorrelation_at_ui_lags",
    "output_noise_psd_one_sided",
    "pam4_unit_voltage_from_delivered_power",
    "pam4_unit_voltage_from_outer_pp",
    "pam4_symbol_sequence",
    "pam4_symbols_to_gray_bits",
    "required_pre_fec_ber_for_iid_post_ber",
    "peak_target_gain_db",
    "rectangular_pulse_response",
    "required_pam4_dp_snr_db",
    "sample_cursor_taps",
    "tx_pulse_shaping_response",
    "train_code_domain_ffe",
    "train_code_domain_dfe",
    "synthesize_symbol_waveform",
    "synthesize_real_noise_from_one_sided_psd",
    "uniform_frequency_grid",
    "worst_case_pam_waveform_peak_v",
    "voltage_papr",
    "zoh_frequency_response",
]
