"""Deterministic PAM4 eye construction from a sampled symbol-pulse response."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import ArrayLike, NDArray


FloatArray = NDArray[np.float64]
IntArray = NDArray[np.int64]


@dataclass(frozen=True)
class EyeDiagram:
    """Eye traces and their associated symbol-center samples."""

    time_ui: FloatArray
    traces_v: FloatArray
    center_samples_v: FloatArray
    symbol_indices: IntArray
    transmitted_symbols: FloatArray
    sampling_index: int


def pam4_symbol_sequence(symbol_count: int, *, seed: int) -> FloatArray:
    """Return a reproducible equiprobable PAM4 sequence in normalized units."""

    if symbol_count < 1:
        raise ValueError("symbol_count must be positive")
    generator = np.random.default_rng(seed)
    levels = np.asarray([-3.0, -1.0, 1.0, 3.0])
    return generator.choice(levels, size=symbol_count).astype(float)


def main_cursor_index(pulse: ArrayLike) -> int:
    """Locate the main cursor, choosing the center of a flat-topped maximum."""

    pulse = np.asarray(pulse, dtype=float)
    if pulse.ndim != 1 or pulse.size < 1:
        raise ValueError("pulse must be a non-empty one-dimensional array")
    magnitude = np.abs(pulse)
    peak = float(np.max(magnitude))
    if not np.isfinite(peak) or peak <= 0.0:
        raise ValueError("pulse must contain a finite nonzero sample")

    peak_indices = np.flatnonzero(np.isclose(magnitude, peak, rtol=1e-10, atol=0.0))
    return int(np.rint(np.mean(peak_indices)))


def _fft_convolve(signal: FloatArray, kernel: FloatArray) -> FloatArray:
    """Return a full linear convolution without the large direct-convolution cost."""

    output_size = signal.size + kernel.size - 1
    fft_size = 1 << (output_size - 1).bit_length()
    result = np.fft.irfft(
        np.fft.rfft(signal, n=fft_size) * np.fft.rfft(kernel, n=fft_size),
        n=fft_size,
    )
    return np.asarray(result[:output_size], dtype=float)


def synthesize_symbol_waveform(
    symbols: ArrayLike,
    symbol_pulse_v: ArrayLike,
    *,
    samples_per_ui: int,
) -> FloatArray:
    """Convolve an upsampled symbol sequence with a sampled symbol pulse."""

    symbols = np.asarray(symbols, dtype=float)
    symbol_pulse_v = np.asarray(symbol_pulse_v, dtype=float)
    if symbols.ndim != 1 or symbols.size < 1 or not np.all(np.isfinite(symbols)):
        raise ValueError("symbols must be finite, non-empty, and one-dimensional")
    if (
        symbol_pulse_v.ndim != 1
        or symbol_pulse_v.size < 1
        or not np.all(np.isfinite(symbol_pulse_v))
    ):
        raise ValueError("symbol pulse must be finite, non-empty, and one-dimensional")
    if samples_per_ui < 1:
        raise ValueError("samples_per_ui must be positive")
    upsampled = np.zeros((symbols.size - 1) * samples_per_ui + 1, dtype=float)
    upsampled[::samples_per_ui] = symbols
    return _fft_convolve(upsampled, symbol_pulse_v)


def eye_diagram_from_symbol_pulse(
    symbols: ArrayLike,
    symbol_pulse_v: ArrayLike,
    *,
    sampling_index: int,
    samples_per_ui: int,
    trace_count: int,
    guard_symbols: int,
    interpolation_samples_per_ui: int = 64,
) -> EyeDiagram:
    """Superimpose two-UI waveform segments generated by a symbol pulse.

    ``symbol_pulse_v`` is the response to one normalized PAM unit, so the
    normalized PAM4 values ``[-3, -1, 1, 3]`` directly set the waveform scale.
    Linear interpolation only smooths the plotted traces; it does not add
    bandwidth or alter the center samples used for numerical reporting.
    """

    symbols = np.asarray(symbols, dtype=float)
    symbol_pulse_v = np.asarray(symbol_pulse_v, dtype=float)
    if symbols.ndim != 1 or symbols.size < 1:
        raise ValueError("symbols must be a non-empty one-dimensional array")
    if symbol_pulse_v.ndim != 1 or symbol_pulse_v.size < 1:
        raise ValueError("symbol_pulse_v must be a non-empty one-dimensional array")
    if not np.all(np.isin(symbols, [-3.0, -1.0, 1.0, 3.0])):
        raise ValueError("symbols must contain only normalized PAM4 levels")
    if samples_per_ui < 1 or interpolation_samples_per_ui < 1:
        raise ValueError("samples-per-UI values must be positive")
    if not 0 <= sampling_index < symbol_pulse_v.size:
        raise ValueError("sampling_index is outside symbol_pulse_v")
    if trace_count < 1:
        raise ValueError("trace_count must be positive")
    if guard_symbols < 1 or 2 * guard_symbols >= symbols.size:
        raise ValueError("guard_symbols must leave at least one interior symbol")

    waveform_v = synthesize_symbol_waveform(
        symbols, symbol_pulse_v, samples_per_ui=samples_per_ui
    )

    first_symbol = guard_symbols
    last_symbol = symbols.size - guard_symbols - 1
    available_count = last_symbol - first_symbol + 1
    actual_trace_count = min(trace_count, available_count)
    symbol_indices = np.unique(
        np.rint(
            np.linspace(first_symbol, last_symbol, actual_trace_count)
        ).astype(np.int64)
    )

    native_time_ui = np.arange(
        -samples_per_ui, samples_per_ui + 1, dtype=float
    ) / samples_per_ui
    time_ui = np.linspace(
        -1.0, 1.0, 2 * interpolation_samples_per_ui + 1, dtype=float
    )
    traces_v = np.empty((symbol_indices.size, time_ui.size), dtype=float)
    center_samples_v = np.empty(symbol_indices.size, dtype=float)
    for trace_index, symbol_index in enumerate(symbol_indices):
        center = sampling_index + int(symbol_index) * samples_per_ui
        native_trace = waveform_v[
            center - samples_per_ui : center + samples_per_ui + 1
        ]
        if native_trace.size != native_time_ui.size:
            raise RuntimeError("eye trace extends outside the synthesized waveform")
        traces_v[trace_index] = np.interp(time_ui, native_time_ui, native_trace)
        center_samples_v[trace_index] = waveform_v[center]

    return EyeDiagram(
        time_ui=time_ui,
        traces_v=traces_v,
        center_samples_v=center_samples_v,
        symbol_indices=symbol_indices,
        transmitted_symbols=symbols[symbol_indices],
        sampling_index=sampling_index,
    )
